import { Discord, Instagram, Logo, Medium, Twitter } from "./images";
import { useRouter } from "next/router";
import { Dialog } from "@headlessui/react";
import { useState } from "react";
//@ts-ignore
import { Link } from "react-scroll";

function Footer({ page }: { page: string }) {
  const router = useRouter();
  let [isOpen, setIsOpen] = useState(false);

  function openModal() {
    setIsOpen(true);
  }
  const footerLogo =
    page === "mint" ? (
      <Link
        onClick={() => router.push("/")}
        to="landing"
        spy={true}
        smooth={true}
        duration={500}
      >
        <Logo />
      </Link>
    ) : (
      <Link to="landing" spy={true} smooth={true} duration={500}>
        <Logo />
      </Link>
    );
  return (
    <div className={page === "mint" ? "footer footer-mint" : "footer"}>
      <div className="container">
        <div className="media">
          <h3>Follow us & spread the word via:</h3>
          <div className="social-media">
            <a
              href="https://twitter.com/ZyggoDistrikt"
              rel="noreferrer"
              target="_blank"
            >
              <Twitter />
            </a>
            <a
              href="https://discord.com/invite/pBzznn5rs7"
              rel="noreferrer"
              target="_blank"
            >
              <Discord />
            </a>
            <a
              href="https://www.instagram.com/zyggodistrikt/"
              rel="noreferrer"
              target="_blank"
            >
              <Instagram />
            </a>
            <a
              href="https://medium.com/@zyggodistrikt"
              rel="noreferrer"
              target="_blank"
            >
              <Medium />
            </a>
          </div>
          <p>
            Reach out & partner with us via{" "}
            <a href="mailto:hello@zyggodistrikt.com?subject = Let’s join forces! = Message">
              hello[at]zyggodistrikt.com
            </a>
          </p>
          <a className="terms" onClick={() => openModal()}>
            Our Terms & Conditions
          </a>
          <Dialog
            open={isOpen}
            onClose={() => setIsOpen(false)}
            className="terms-modal"
          >
            <Dialog.Overlay className="overlay" />

            <div className="modal-body">
              <Dialog.Title className="modal-title">
                TERMS & CONDITIONS
              </Dialog.Title>
              <Dialog.Description className="modal-description">
                <p>
                  Zyggo Distrikt provides collections of digital artworks (NFTs)
                  running on the Ethereum blockchain. The current website is an
                  interface allowing participants to exchange digital
                  collectibles. Users are entirely responsible for the safety
                  and management of their own private Ethereum wallets and
                  validating all transactions and contracts generated by this
                  website before approval. Furthermore, as the Zyggo District
                  smart contracts run on the Ethereum network, there is no
                  ability to undo, reverse, or restore any transactions.
                </p>
                <p>
                  This website and its connected services are provided “as is”
                  and “as available” without warranty of any kind. By using this
                  website you are accepting sole responsibility for any and all
                  transactions involving Zyggo Distrikt NFT collections and
                  digital collectibles.
                </p>
                <p>OWNERSHIP</p>
                <p>
                  i The ownership of a Purchased Zyggo Distrikt NFT is governed
                  by a smart contract on Ethereum, which cannot be reversed or
                  modified in any way whatsoever.
                </p>
                <p>
                  ii. The license granted applies up to the extent that Zyggo
                  Distrikt NFT Owner continues to own a Purchased Zyggo Distrikt
                  NFT. If at any time Zyggo Distrikt NFT Owner sells, trades,
                  donates, gives away, transfers, or otherwise disposes of
                  her/his Purchased Zyggo Distrikt NFT for any reason, the
                  license granted in this section will immediately expire with
                  respect to such Purchased Zyggo Distrikt NFT without the
                  requirement of notice, and User (former Zyggo Distrikt NFT
                  Owner) will have no further rights in or to such Artwork.
                </p>
                <p>
                  iii. Commercial Use. Subject to her/his continued compliance
                  with the terms of the Agreement, Service Provider grants Zyggo
                  Distrikt NFT Owner a limited, worldwide, exclusive,
                  transferable license to use, copy, and display the Artwork
                  associated with Purchased NFTs for the purpose of
                  commercializing User’s own merchandise that includes,
                  contains, or consists of the Artwork.
                </p>
                <p>
                  For the sake of clarity, nothing in this section will be
                  deemed to restrict Zyggo Distrikt NFT Owner from:
                </p>
                <p>
                  ▪ Owning or operating a marketplace that permits the use and
                  sale of Zyggo Distrikt NFT generally, provided that the
                  marketplace cryptographically verifies each Zyggo Distrikt NFT
                  Owner’s rights to display the Artwork to ensure that only the
                  actual owner can display such Artwork;{" "}
                </p>
                <p>
                  ▪ Owning or operating a third-party website or application
                  that permits the inclusion, involvement, or participation of
                  NFTs generally, provided that the third-party website or
                  application cryptographically verifies each Zyggo Distrikt NFT
                  Owner’s rights to display the Artwork to ensure that only the
                  actual owner can display such Artwork, and provided that such
                  Artwork is no longer visible once such Zyggo Distrikt NFT
                  Owner leaves the website/application.
                </p>
                <p className="align-right mtop">
                  ZyggoDistrikt4UkraineNFT Smart Contract Address:
                </p>
                <p className="align-right">
                  0xd96780f3dc4bf26ddea3d87153e4e2a315689c65
                </p>
              </Dialog.Description>
              <div className="modal-footer">
                <button onClick={() => setIsOpen(false)}>I Understand</button>
              </div>
            </div>
          </Dialog>
          <span>© 2022 Zyggo Distrikt</span>
        </div>
        <div className="verified">
          <div className="logo">{footerLogo}</div>
          <p>
            VERIFIED SMART CONTRACT ADDRESS: {"\n"}
            <a
              href="https://etherscan.io/address/0xd96780f3dc4bf26ddea3d87153e4e2a315689c65"
              rel="noreferrer"
              target="_blank"
            >
              0xd96780f3dc4bf26ddea3d87153e4e2a315689c65
            </a>
          </p>
          <span>
            powered by{" "}
            <a href="http://www.trilld.com/" rel="noreferrer" target="_blank">
              <strong>trilld</strong>
            </a>{" "}
          </span>
        </div>
      </div>
    </div>
  );
}

export default Footer;
